name: Hopping Turtle CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: ['18.x', '20.x']

        steps:
        - uses: actions/checkout@v5

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4 # setup-node does not use sparse-checkout
          with:
            node-version: ${{ matrix.node-version }}
        
        - name: Navigate to hopping-turtle directory
          run: cd hopping-turtle

        - name: Install Dependencies
          working-directory: ./hopping-turtle
          run: npm install

        - name: Run Linter and Basic Tests (if present)
          working-directory: ./hopping-turtle
          run: |
            npm run lint || true
            npm test || true

        - name: Build Expo App (Check it compiles)
          working-directory: ./hopping-turtle
          run:
            npx expo export 
